name: EDGEPhotography
favicon: null
layout_spectrum: 0.25429236073978245
typography_spectrum: 0.88482
title: EDGE Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8d9d2'
    - '#00b7aa'
    - '#b97d63'
    - '#007177'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
