name: EDGEPhotography
favicon: null
layout_spectrum: 0.25429236073978245
typography_spectrum: 0.7240248005837202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9838722432032228
  lightness: 0.4850468225777149
  saturation: 0.5269474522210658
  rhythmicContrast: 0.038171465042978525
purpose: []
